"""CLI constants — exit codes, error category identifiers, and registry defaults."""

from ..common.taxonomy_core_vo import PortNumber

REGISTRY_DEFAULT_PORT: PortNumber = PortNumber(9876)

EXIT_SUCCESS = 0
EXIT_VALIDATION = 2
EXIT_UPSTREAM = 3
EXIT_UNEXPECTED = 4

CATEGORY_VALIDATION = "validation_error"
CATEGORY_CONFIGURATION = "configuration_error"
CATEGORY_NOT_FOUND = "not_found"
CATEGORY_CAPACITY = "capacity"
CATEGORY_TIMEOUT = "timeout"
CATEGORY_SECURITY = "security_violation"
CATEGORY_CONNECTION = "connection"
CATEGORY_STATE = "state"
CATEGORY_TASK = "task"
CATEGORY_UNEXPECTED = "unexpected"

ERROR_CATEGORY_MAP: dict[str, int] = {
    CATEGORY_VALIDATION: EXIT_VALIDATION,
    CATEGORY_CONFIGURATION: EXIT_VALIDATION,
    CATEGORY_NOT_FOUND: EXIT_UPSTREAM,
    CATEGORY_CAPACITY: EXIT_UPSTREAM,
    CATEGORY_TIMEOUT: EXIT_UPSTREAM,
    CATEGORY_SECURITY: EXIT_UPSTREAM,
    CATEGORY_CONNECTION: EXIT_UPSTREAM,
    CATEGORY_STATE: EXIT_UPSTREAM,
    CATEGORY_TASK: EXIT_UPSTREAM,
}
