"""Scene domain shared taxonomy constants and contracts."""

from .contract_scene_aggregate import ISceneAggregate
from .contract_scene_cleanup_protocol import SceneCleanupProtocol
from .contract_scene_inspection import SceneInspectionPort
from .contract_scene_operate_protocol import SceneOperateProtocol
from .taxonomy_scene_constant import (
    CLEANUP_CONFIRMATION_REQUIRED,
    CLEANUP_TIMEOUT_SECONDS,
    DEFAULT_CHILD_HANDLING_POLICY,
    DEFAULT_DEPENDENT_HANDLING_POLICY,
    DEFAULT_DRY_RUN_MODE,
    DEFAULT_INCLUDE_HIDDEN_OBJECTS,
    DEFAULT_PRESERVATION_LIST,
    INSPECTION_TIMEOUT_SECONDS,
    MAX_INSPECTION_DETAIL_LIMIT,
    PROTECTED_OBJECT_POLICY_ACTIVE_CAMERA,
    PROTECTED_OBJECT_POLICY_LIGHTS,
    PROTECTED_OBJECT_POLICY_PROTECTED,
    PROTECTED_OBJECT_POLICY_SOLE_CAMERA,
)

__all__ = [
    "SceneCleanupProtocol",
    "SceneInspectionPort",
    "SceneOperateProtocol",
    "ISceneAggregate",
    "CLEANUP_CONFIRMATION_REQUIRED",
    "CLEANUP_TIMEOUT_SECONDS",
    "DEFAULT_CHILD_HANDLING_POLICY",
    "DEFAULT_DEPENDENT_HANDLING_POLICY",
    "DEFAULT_DRY_RUN_MODE",
    "DEFAULT_INCLUDE_HIDDEN_OBJECTS",
    "DEFAULT_PRESERVATION_LIST",
    "INSPECTION_TIMEOUT_SECONDS",
    "MAX_INSPECTION_DETAIL_LIMIT",
    "PROTECTED_OBJECT_POLICY_ACTIVE_CAMERA",
    "PROTECTED_OBJECT_POLICY_LIGHTS",
    "PROTECTED_OBJECT_POLICY_PROTECTED",
    "PROTECTED_OBJECT_POLICY_SOLE_CAMERA",
]
