"""Gateway domain — Taxonomy layer: VOs, Errors for connection, transport, queue, execution."""

from .taxonomy_gateway_error import (
    AuthenticationError,
    ChannelConflictError,
    ConnectionError,
    GatewayError,
    PayloadLimitError,
    ProtocolVersionMismatchError,
    SecurityViolationError,
    TimeoutError,
    TransportParseError,
)
from .taxonomy_gateway_vo import (
    CodeExecutionResultVO,
    CodeExecutionVO,
    ConnectionConfigVO,
    ConnectionResultVO,
    ConnectionState,
    ConnectionStatusVO,
    QueueStatusVO,
    SceneOperationResultVO,
    SceneOperationVO,
    TransportMessageVO,
    TransportResultVO,
    TransportType,
)

__all__ = [
    "GatewayError",
    "ConnectionError",
    "TimeoutError",
    "ProtocolVersionMismatchError",
    "AuthenticationError",
    "ChannelConflictError",
    "SecurityViolationError",
    "TransportParseError",
    "PayloadLimitError",
    "ConnectionState",
    "TransportType",
    "ConnectionConfigVO",
    "ConnectionResultVO",
    "ConnectionStatusVO",
    "TransportMessageVO",
    "TransportResultVO",
    "SceneOperationVO",
    "SceneOperationResultVO",
    "QueueStatusVO",
    "CodeExecutionVO",
    "CodeExecutionResultVO",
]
