"""Cross-platform installer for the Blender Arwaky CLI wrappers.

Installs ``blender-arwaky`` and ``blender-cli`` as global commands by
generating small wrapper scripts in the user's local bin directory
(``~/.local/bin`` on Unix, ``%USERPROFILE%\\.local\\bin`` on Windows).

Replaces the previous ``install_cli.sh`` Bash script.

Usage:
    uv run python scripts/install/install_cli_wrappers.py
"""

from __future__ import annotations

import os
import shutil
import stat
import subprocess
import sys
from pathlib import Path
from typing import Final

IS_WINDOWS: Final[bool] = sys.platform.startswith("win")
PROJECT_ROOT: Final[Path] = Path(__file__).resolve().parent.parent.parent
WRAPPER_COMMANDS: Final[tuple[str, ...]] = ("blender-arwaky", "blender-cli", "blender-mcp")


def get_xdg_venv_dir() -> Path:
    """Return physical XDG virtual environment directory."""
    if os.environ.get("XDG_DATA_HOME"):
        return Path(os.environ["XDG_DATA_HOME"]) / "blender-arwaky" / "venv"
    return Path.home() / ".local" / "share" / "blender-arwaky" / "venv"


def detect_or_create_venv() -> Path:
    """Return the physical XDG virtualenv and ensure project root symlinks exist for IDEs."""
    venv_dir = get_xdg_venv_dir()
    bin_dir = "Scripts" if IS_WINDOWS else "bin"
    py_exe = "python.exe" if IS_WINDOWS else "python"
    
    if not (venv_dir / bin_dir / py_exe).exists():
        print(f"[*] Creating physical virtual environment at {venv_dir} ...")
        venv_dir.parent.mkdir(parents=True, exist_ok=True)
        import venv

        builder = venv.EnvBuilder(with_pip=True, clear=False, symlinks=not IS_WINDOWS)
        builder.create(str(venv_dir))

    # Setup project root symlinks for IDEs/agents
    if not IS_WINDOWS:
        for name in (".venv", "venv"):
            target = PROJECT_ROOT / name
            if target.is_symlink():
                try:
                    if target.resolve() == venv_dir.resolve():
                        continue
                    target.unlink()
                except OSError:
                    target.unlink(missing_ok=True)
            elif target.exists():
                if target.is_dir():
                    shutil.rmtree(target, ignore_errors=True)
                else:
                    target.unlink(missing_ok=True)
            try:
                target.symlink_to(venv_dir)
                print(f"[+] Created IDE symlink: {target} -> {venv_dir}")
            except OSError as err:
                print(f"[!] Warning: Could not create {target} symlink: {err}")

    return venv_dir


def venv_python(venv: Path) -> Path:
    """Return the Python executable inside the venv."""
    bin_dir = "Scripts" if IS_WINDOWS else "bin"
    exe = "python.exe" if IS_WINDOWS else "python"
    return venv / bin_dir / exe


def venv_executable(venv: Path, name: str) -> Path:
    """Return the console-script entry point inside the venv."""
    bin_dir = "Scripts" if IS_WINDOWS else "bin"
    suffix = ".exe" if IS_WINDOWS else ""
    return venv / bin_dir / f"{name}{suffix}"


def install_package_editable(venv: Path) -> None:
    """Install the project in editable mode using ``uv`` if available."""
    print(f"[*] Installing blender-arwaky (editable) into {venv} ...")
    if shutil.which("uv") is not None:
        print("    Using uv for fast installation.")
        subprocess.run(
            ["uv", "pip", "install", "--python", str(venv_python(venv)), "-e", "."],
            cwd=PROJECT_ROOT,
            check=True,
        )
        return
    pip = venv_python(venv)
    subprocess.run(
        [str(pip), "install", "-e", str(PROJECT_ROOT)],
        cwd=PROJECT_ROOT,
        check=True,
    )


def local_bin_dir() -> Path:
    """Return the platform-appropriate user-local bin directory."""
    if os.environ.get("XDG_BIN_HOME"):
        return Path(os.environ["XDG_BIN_HOME"])
    return Path.home() / ".local" / "bin"


def write_unix_wrapper(target: Path, wrapper: Path) -> None:
    """Write a POSIX shell wrapper that execs ``target``."""
    content = f'#!/bin/sh\n# Auto-generated by install_cli_wrappers.py — do not edit.\nexec "{target}" "$@"\n'
    wrapper.write_text(content, encoding="utf-8")
    wrapper.chmod(wrapper.stat().st_mode | stat.S_IEXEC | stat.S_IXGRP | stat.S_IXOTH)


def write_windows_wrapper(target: Path, wrapper: Path) -> None:
    """Write a Windows .cmd wrapper that invokes ``target``."""
    content = f'@echo off\r\nREM Auto-generated by install_cli_wrappers.py — do not edit.\r\n"{target}" %*\r\n'
    wrapper.write_text(content, encoding="utf-8")


def install_wrappers(venv: Path) -> list[Path]:
    """Create wrapper scripts in the local bin directory; return created paths."""
    bin_dir = local_bin_dir()
    bin_dir.mkdir(parents=True, exist_ok=True)
    created: list[Path] = []
    for cmd in WRAPPER_COMMANDS:
        target = venv_executable(venv, cmd)
        if not target.exists():
            print(f"[!] WARNING: {target} not found — did the install step succeed?")
            continue
        wrapper = bin_dir / (f"{cmd}.cmd" if IS_WINDOWS else cmd)
        if IS_WINDOWS:
            write_windows_wrapper(target, wrapper)
        else:
            write_unix_wrapper(target, wrapper)
        print(f"[+] Wrote wrapper: {wrapper} -> {target}")
        created.append(wrapper)
    return created


def warn_path(bin_dir: Path) -> None:
    """Print a warning if ``bin_dir`` is not on ``PATH``."""
    path_env = os.environ.get("PATH", "")
    if str(bin_dir) not in path_env.split(os.pathsep):
        print(f"[!] WARNING: {bin_dir} is not on your PATH.")
        if IS_WINDOWS:
            print("    Add it via System Properties -> Environment Variables.")
        else:
            print("    Add this line to your ~/.bashrc or ~/.zshrc:")
            print('    export PATH="$HOME/.local/bin:$PATH"')


def main() -> int:
    print("=== Blender Arwaky CLI Wrapper Installer ===")
    print(f"Project Root: {PROJECT_ROOT}")
    venv = detect_or_create_venv()
    print(f"Virtual Env:  {venv}")
    print()
    install_package_editable(venv)
    install_wrappers(venv)
    print()
    print("=== Installation Complete ===")
    print("You can now run:")
    for cmd in WRAPPER_COMMANDS:
        print(f"  {cmd} --help")
    warn_path(local_bin_dir())
    return 0


if __name__ == "__main__":
    sys.exit(main())