"""MCP Tool 1: execute_command — Universal action executor.

FR-MCP-001: Expose MCP Tools — register via contract protocol
FR-MCP-002: Route Tool Calls — dispatcher aggregate via routing protocol
FR-MCP-003: Format MCP Responses — unified envelope via response protocol
"""

import logging
from typing import Any

from modules.shared.src.mcp.contract_mcp_protocol import (
    McpResponseProtocol,
    McpRoutingProtocol,
)

logger = logging.getLogger("BlenderMCPServer")


class ExecuteCommandHandler:
    """Surface handler for execute_command MCP tool.

    Delegates all logic to contract protocols — zero business logic.
    """

    def __init__(
        self,
        routing: McpRoutingProtocol,
        response: McpResponseProtocol,
    ) -> None:
        self._routing = routing
        self._response = response

    @staticmethod
    def register_execute_command(mcp):
        """Register the execute_command tool (MCP Tool #1)."""
        from modules.mcp.src.root_mcp_container import create_mcp_feature

        container = create_mcp_feature()

        async def execute_command(
            action: str,
            args: dict[str, Any] | None = None,
        ) -> dict[str, Any]:
            """Execute ANY BlenderArwaky action via dispatcher aggregate."""
            if args is None:
                args = {}

            # Surface-level validation only (FR-MCP-002)
            errors = await container.routing.validate_tool_input(
                "execute_command", {"action": action, "args": args}
            )
            if errors:
                return await container.response.format_response(
                    result={"error": "; ".join(errors)},
                    tool_name="execute_command",
                    tracking_id="",  # Generated by response formatter
                    error_category="validation",
                )

            # Route to dispatcher aggregate via protocol (FR-MCP-002)
            try:
                result = await container.routing.route_tool_call(
                    tool_name="execute_command",
                    payload={"action": action, "args": args},
                )
                return await container.response.format_response(
                    result=result,
                    tool_name="execute_command",
                    tracking_id="",
                )
            except Exception as e:
                logger.error("Execution failed for '%s': %s", action, e, exc_info=True)
                return await container.response.format_response(
                    result={"error": str(e)},
                    tool_name="execute_command",
                    tracking_id="",
                    error_category="execution",
                )

        mcp.tool()(execute_command)
