"""MCP Tool 1: execute_command — Universal action executor.

FR-MCP-001: Expose MCP Tools — register via contract protocol
FR-MCP-002: Route Tool Calls — dispatcher aggregate via routing protocol
FR-MCP-003: Format MCP Responses — unified envelope via response protocol
"""

import logging

from modules.shared.src.mcp.contract_mcp_protocol import (
    McpResponseProtocol,
    McpRoutingProtocol,
)

logger = logging.getLogger("BlenderMCPServer")

#: Maximum allowed payload size for tool call arguments (bytes)
MAX_PAYLOAD_SIZE = 1_000_000  # 1MB


class ExecuteCommandSurface:
    """Surface handler for execute_command MCP tool.

    Delegates all logic to contract protocols — zero business logic.
    """

    def __init__(
        self,
        routing: McpRoutingProtocol,
        response: McpResponseProtocol,
    ) -> None:
        self._routing = routing
        self._response = response

    @staticmethod
    def register(mcp, container) -> None:
        """Register execute_command tool with MCP server."""

        async def execute_command(
            action: str,
            args: dict[str, object] | None = None,
        ) -> dict[str, object]:
            """Execute ANY BlenderArwaky action via dispatcher aggregate."""
            if args is None:
                args = {}

            # Oversized payload protection (FR-MCP-002)
            import json
            payload_size = len(json.dumps({"action": action, "args": args}).encode("utf-8"))
            if payload_size > MAX_PAYLOAD_SIZE:
                return await container.response.format_response(
                    result={"error": f"Payload exceeds maximum size of {MAX_PAYLOAD_SIZE} bytes"},
                    tool_name="execute_command",
                    tracking_id="",
                    error_category="validation",
                )

            # Surface-level validation only (FR-MCP-002)
            errors = await container.routing.validate_tool_input(
                "execute_command", {"action": action, "args": args}
            )
            if errors:
                return await container.response.format_response(
                    result={"error": "; ".join(errors)},
                    tool_name="execute_command",
                    tracking_id="",  # Generated by response formatter
                    error_category="validation",
                )

            # Route to dispatcher aggregate via protocol (FR-MCP-002)
            try:
                result = await container.routing.route_tool_call(
                    tool_name="execute_command",
                    payload={"action": action, "args": args},
                )
                return await container.response.format_response(
                    result=result,
                    tool_name="execute_command",
                    tracking_id="",
                )
            except Exception as e:
                logger.error("Execution failed for '%s': %s", action, e, exc_info=True)
                return await container.response.format_response(
                    result={"error": str(e)},
                    tool_name="execute_command",
                    tracking_id="",
                    error_category="execution",
                )

        mcp.tool()(execute_command)
