"""Compile-time constants for plugin lifecycle and result categories."""

PLUGIN_PROVIDER_TYPE_BLENDER_ADDON = "blender_addon"
PLUGIN_STATUS_AVAILABLE = "available"
PLUGIN_STATUS_UNAVAILABLE = "unavailable"
PLUGIN_STATUS_INCOMPATIBLE = "incompatible"
PLUGIN_STATUS_UNSUPPORTED = "unsupported"
PLUGIN_STATUS_FAILED = "failed"
PLUGIN_STATUS_SUCCESS = "success"
PLUGIN_STATUS_NOT_FOUND = "not_found"
PLUGIN_ACTION_DISCOVER = "plugin.discover"
PLUGIN_ACTION_HEALTH_CHECK = "plugin.health_check"
PLUGIN_ACTION_LIST = "plugin.list"
PLUGIN_ACTION_DOWNLOAD = "plugin.download"
PLUGIN_ACTION_VERIFY = "plugin.verify"
PLUGIN_ACTION_INSTALL = "plugin.install"
PLUGIN_ACTION_ENABLE = "plugin.enable"
PLUGIN_ACTION_DISABLE = "plugin.disable"
PLUGIN_ACTION_REMOVE = "plugin.remove"
PLUGIN_STATUS_VERIFIED = "verified"
PLUGIN_STATUS_INSTALLED = "installed"
PLUGIN_STATUS_BLOCKED = "blocked"
